# Generated by Django 3.1.3 on 2020-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care_House_Infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('house_address_one', models.CharField(max_length=100)),
                ('house_address_two', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('house_number', models.IntegerField(default=0)),
                ('house_email', models.EmailField(default='', max_length=254)),
                ('number_of_beds', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('number_of_bathrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('house_type_of_accommodation', models.CharField(choices=[('Detached', 'Detached'), ('Semi-Detached', 'Semi-Detached'), ('Terraced', 'Terraced'), ('End of Terrace', 'End of Terrace'), ('Flat', 'Flat'), ('Studio Flat', 'Studio Flat'), ('Split-Level Flat', 'Split-Level Flat'), ('Converted Flat', 'Converted Flat'), ('Maisonette', 'Maisonette'), ('Cottage', 'Cottage'), ('Bungalow', 'Bungalow'), ('Mansion', 'Mansion')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Care House Information',
            },
        ),
        migrations.AlterField(
            model_name='yp_general_information',
            name='yp_ethnicity',
            field=models.CharField(choices=[('White - English/Welsh/Scottish/Northern Irish/British', 'White - English/Welsh/Scottish/Northern Irish/British'), ('White - Irish', 'White - Irish'), ('White - Gypsy or Irish Traveller', 'White - Gypsy or Irish Traveller'), ('White - Any other White background', 'White - Any other White background'), ('Mixed - White and Black Caribbean', 'Mixed - White and Black Caribbean'), ('Mixed - White and Black African', 'Mixed - White and Black African'), ('Mixed - White and Asian', 'Mixed - White and Asian'), ('Mixed - Any other Mixed/Multiple ethnic background', 'Mixed - Any other Mixed/Multiple ethnic background'), ('Asian - Indian', 'Asian - Indian'), ('Asian - Pakistani', 'Asian - Pakistani'), ('Asian - Bangladeshi', 'Asian - Bangladeshi'), ('Asian - Chinese', 'Asian - Chinese'), ('Asian - Any other Asian background', 'Asian - Any other Asian background'), ('Black - African', 'Black - African'), ('Black - Caribbean', 'Black - Caribbean'), ('Black - Any other Black/African/Caribbean background', 'Black - Any other Black/African/Caribbean background'), ('Arab', 'Arab'), ('Any other ethnic group', 'Any other ethnic group')], default='White - English/Welsh/Scottish/Northern Irish/British', max_length=100),
        ),
    ]
