# Generated by Django 3.1.3 on 2020-12-05 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20201205_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='care_house_infomation',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
