# Generated by Django 3.1.3 on 2020-12-06 21:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_remove_yp_ipa_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='YP_Relationships_Associates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_of_kin', models.CharField(max_length=100)),
                ('relationship_wth_next_kin', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.IntegerField(default=0)),
                ('close_friend_name', models.CharField(max_length=100)),
                ('contact_phone_close_friend', models.IntegerField(default=0)),
                ('work_school_contact_phone', models.IntegerField(default=0)),
                ('place_worship_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('places_known_frequent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('yp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.yp_general_information')),
            ],
            options={
                'verbose_name_plural': 'Young Person Relationships and Associates',
            },
        ),
    ]
