# Generated by Django 3.1.3 on 2020-12-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_yp_relationships_associates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local_authority',
            name='postcode',
        ),
    ]
