# Generated by Django 3.1.3 on 2020-12-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_local_authority_postcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_Pic',
        ),
    ]
