# Generated by Django 3.1.3 on 2020-12-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20201210_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='yp_general_information',
            name='parenthood',
            field=models.CharField(choices=[('Young Parent', 'Young Parent'), ('Not a Parent', 'Not a Parent')], default='No', max_length=15),
        ),
    ]
