# Generated by Django 3.1.3 on 2020-11-28 18:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notes', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('detailed_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='admission.yp_general_information')),
            ],
            options={
                'verbose_name_plural': 'Young Person Notes',
            },
        ),
    ]
