# Generated by Django 3.1.3 on 2020-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='contact_type',
            field=models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('Instant Messaging', 'Instant Messaging'), ('Task', 'Task'), ('Admin', 'Admin')], default='Face-to-Face', max_length=100),
        ),
    ]
