# Generated by Django 3.1.3 on 2020-12-14 22:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_yp_general_information_parenthood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_notes_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notes', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location_id', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('Instant Messaging', 'Instant Messaging'), ('Task', 'Task'), ('Admin', 'Admin')], default='Face-to-Face', max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('question_1a', models.CharField(max_length=100)),
                ('question_1b', models.CharField(max_length=100)),
                ('question_1c', models.CharField(max_length=100)),
                ('question_1d', models.CharField(max_length=100)),
                ('question_1e', models.CharField(max_length=100)),
                ('question_1f', models.CharField(max_length=100)),
                ('question_2', models.CharField(max_length=100)),
                ('question_3', models.CharField(max_length=100)),
                ('question_4', models.CharField(max_length=100)),
                ('question_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('question_6', models.CharField(max_length=100)),
                ('question_7', models.CharField(max_length=100)),
                ('question_8', models.CharField(max_length=100)),
                ('detailed_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_notes', to='admission.yp_general_information')),
            ],
            options={
                'verbose_name_plural': 'Young Parent Notes',
            },
        ),
    ]
